### ISSUE TITLE
Error when chmod'ing lib after setting up wxpython

### ISSUE THREAD

**Issue by kejadlen** [metacollin/homebrew-kicad#2]
```
==> /usr/bin/python setup.py install --prefix=/usr/local/Cellar/wxkicad/3.0.2.0 WXPORT=osx
Error: no implicit conversion from nil to integer
Please report this bug:
    http://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1327:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1327:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/usr/local/Library/Taps/metacollin/homebrew-kicad/wxkicad.rb:72:in `install'
```

**Comment by metacollin** [comment]
Hi, I fixed this one before you actually posted this issue. :)  It looks like you ran brew update right in the middle of the frenzy of some last minute commits I did when I realized I forgot something, then more commits to fix things the first commits broke or typos.  It's uh not the best time to attempt to build anything from this tap.

Wait a few more hours for the dust to settle on my end, then run brew update and try :).  I was hoping I could sneak these in before anyone even noticed I updated the readme, but I was too slow.

**Comment by kejadlen** [comment]
Tracking some of the issues I'm hitting:

```
Please, set your name with the 'whoami' command.
E.g. bzr whoami "Your Name <name@example.com>"
make[2]: *** [../.downloads-by-cmake/boost_1_57_0/src/boost-stamp/boost-bzr_commit_boost] Error 3
make[1]: *** [CMakeFiles/boost.dir/all] Error 2
make: *** [all] Error 2
```

Solution: initialize bazaar as described in the error.

```
==> make install
  cvpcb/cmake_install.cmake:69 (fixup_bundle)
  cmake_install.cmake:59 (include)


make: *** [install] Error 1
```

Not sure where to start looking to fix this one, though.

**Comment by kejadlen** [comment]
It works now! Much thanks for your work on this.
